name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Vercel Actions
        uses: nexterias/actions-vercel@v2.0.0
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          org-id: ${{ secrets.ercel_org_id }}
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          production: true
